name: ORLOV
favicon: null
layout_spectrum: 0.35112759633921087
typography_spectrum: 0.02420912403613329
title: ORLOV jewelry - a precious dream
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.31253497395664454
  lightness: 0.8768957008142024
  saturation: 0.5362979942001402
  rhythmicContrast: 0.7876193239353597
purpose: []
